version: 2
updates:

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    target-branch: "master"
    allow:
      - dependency-type: direct
    schedule:
      interval: "daily"
    versioning-strategy: increase
    commit-message:
      prefix: "NPM"
      prefix-development: "NPM Dev"
      include: "scope"
    labels:
      - "dependencies"
      - "javascript"
